# Generated by Django 5.2.8 on 2025-11-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity_score', models.FloatField()),
                ('relevance_score', models.FloatField()),
                ('accuracy_score', models.FloatField()),
                ('completeness_score', models.FloatField()),
                ('empathy_score', models.FloatField()),
                ('sentiment', models.CharField(max_length=20)),
                ('fallback_frequency', models.IntegerField()),
                ('resolution', models.BooleanField()),
                ('escalation_needed', models.BooleanField()),
                ('response_time_avg', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='conversations.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'user'), ('ai', 'ai')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
        ),
    ]
